CONFIG_NRF_REGTOOL_TOML_CONFIG_FILES="uicr/nrf54h20dk_nrf54h20_cpuapp.toml"
CONFIG_RTT_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_COREMARK_ITERATIONS=10000

CONFIG_LOG_BACKEND_UART=n
CONFIG_UART_CONSOLE=n
CONFIG_CONSOLE=n

CONFIG_APP_BUILD_MULTICORE=n
CONFIG_LOG=n
CONFIG_LOG_FRONTEND=n
CONFIG_LOG_FRONTEND_ONLY=n
CONFIG_LOG_PRINTK=n
CONFIG_CBPRINTF_FP_SUPPORT=n
CONFIG_CONSOLE=n
CONFIG_PRINTK_SYNC=n

CONFIG_LOG_FRONTEND_CORESIGHT_STM=n
CONFIG_LOG_FRONTEND_CORESIGHT_STM_FSC=n
