language: c

compiler: gcc

env:
    global:
        - SDK=0.9.1
        - SANITYCHECK_OPTIONS=" --inline-logs -R"
        - SANITYCHECK_OPTIONS_RETRY="${SANITYCHECK_OPTIONS} --only-failed --outdir=out-2nd-pass"
        - ZEPHYR_SDK_INSTALL_DIR=/opt/sdk/zephyr-sdk-0.9.1
        - ZEPHYR_GCC_VARIANT=zephyr
        - USE_CCACHE=1

build:
    cache: false
    pre_ci_boot:
        image_name: zephyrprojectrtos/ci
        image_tag: master.27
        pull: true
        options: "-e HOME=/home/buildslave --privileged=true --tty --net=bridge --user buildslave"

    ci:
      - export CCACHE_DIR=${SHIPPABLE_BUILD_DIR}/ccache/.ccache
      - git rebase origin/${PULL_REQUEST_BASE_BRANCH}
      - wget -q https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz;
      - tar xf cmake-3.9.1-Linux-x86_64.tar.gz;
      - sudo cp -a cmake-3.9.1-Linux-x86_64/bin/* /usr/local/bin/;
      - sudo cp -a cmake-3.9.1-Linux-x86_64/share/* /usr/local/share/;
      - cmake -version
      - source zephyr-env.sh
      - cd $ZEPHYR_BASE/scripts
      - mkdir build && cd build
      - cmake .. && make
      - export PREBUILT_HOST_TOOLS=$(pwd)
      - export BOARD=nrf52_pca10040
      - cd $ZEPHYR_BASE/samples/bluetooth/beacon
      - mkdir build && cd build
      - cmake -DCMAKE_TOOLCHAIN_FILE=$ZEPHYR_BASE/cmake/toolchain.cmake ..
      - make

integrations:
  notifications:
    - integrationName: slack_integration
      type: slack
      recipients:
        - "#ci"
      branches:
        only:
          - master
      on_success: never
      on_failure: always
    - integrationName: email
      type: email
      recipients:
        - builds@zephyrproject.org
      branches:
        only:
          - master
          - net
          - bluetooth
          - arm
      on_success: never
      on_failure: never
