set(TOOLCHAIN_HOME /usr) # TODO

set(COMPILER gcc)

set(SYSROOT_TARGET linux) # TODO

set(CROSS_COMPILE ${TOOLCHAIN_HOME}/bin/)
set(SYSROOT_DIR   ${TOOLCHAIN_HOME}/${SYSROOT_TARGET}) # TODO

#set(CMAKE_C_FLAGS 	-m32   CACHE INTERNAL " " FORCE)
#set(CMAKE_CXX_FLAGS 	-m32   CACHE INTERNAL " " FORCE)
#set(CMAKE_SHARED_LINKER_FLAGS -m32 CACHE INTERNAL " " FORCE)

